- hosts: localhost
  vars:
    varOne: 'HELLO'
    varTwo: 'hello'
  tasks:
    - name: Ansible Template Example
      template:
        src: hello_world.j2
        dest: /home/insignia/Documents/bhavesh-work/ansible-sample/hello.txt
