- name: Get Java Zip
      get_url:
        url: https://download.java.net/java/GA/jdk10/10.0.1/fb4372174a714e6b8c52526dc134031e/10/openjdk-10.0.1_linux-x64_bin.tar.gz
        dest: /home/insignia/Documents/bhavesh-work/open-jdk10.tar.gz

- name: Make Java 10 Directory
      file:
        path: /home/insignia/Documents/JAVA/java10
        state: directory

- name: Unpack Zip
      unarchive:
        dest: /home/insignia/Documents/JAVA/java10
        src: /home/insignia/Documents/bhavesh-work/open-jdk10.tar.gz
        remote_src: yes

- name: set java home as environment variable
      blockinfile:
        insertafter: EOF
        path: /etc/environment
        block: export JAVA_HOME=/usr/lib/java10/jdk-10.0.1
